# Generated by Django 5.0.6 on 2024-12-18 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Voucher', '0002_voucheruser'),
        ('customer', '0009_user_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='voucheruser',
            unique_together={('user', 'voucher')},
        ),
    ]
